In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [6]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [8]:
data = pd.concat([data.drop('Geography' ,axis=1), geo_encoded_df], axis=1)

In [9]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [10]:
x = data.drop('EstimatedSalary',axis =1)
y = data['EstimatedSalary']

In [11]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [15]:
scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

In [16]:
with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)
with open('scale.pkl', 'rb') as file:
    scale = pickle.load(file)

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
model = Sequential([
    # HL1 connected to input layer
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),  # HL2
    Dense(1)  # Output layer ... no activation as default is linear 
]
)

# compile the model
model.compile(optimizer='adam', loss="mean_absolute_error",metrics=['mae'])

model.summary()

d:\Ann Project Me\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback= TensorBoard(log_dir = log_dir , histogram_freq=1)

In [20]:
early_stopping_callback = EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True)

In [21]:
# Training model
histoy = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test), epochs=100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 100381.2266 - mae: 100381.2266 - val_loss: 98526.8281 - val_mae: 98526.8281
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99659.0625 - mae: 99659.0625 - val_loss: 97061.6250 - val_mae: 97061.6250
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97112.0781 - mae: 97112.0781 - val_loss: 93306.4062 - val_mae: 93306.4062
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92100.0938 - mae: 92100.0938 - val_loss: 87028.8281 - val_mae: 87028.8281
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 84738.3125 - mae: 84738.3125 - val_loss: 78777.6562 - val_mae: 78777.6562
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 75945.2812 - mae: 75945.2812 - val_loss: 70022.7422 - val_mae: 70022.7422
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 67292.7891 - mae: 67292.7891 - val_loss: 62256.8633 - val_mae: 62256.8633
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 60124.4102 - mae: 60124.4102 - val_loss: 56423.2383 - val_mae: 56423.2383
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55292.0703 - mae: 55292.0703 - val_loss: 52977.5625 - val_mae: 52977.5625
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52541.6914 - mae: 52541.6914 - val_loss: 51300.3086 - val_mae: 51300.3086
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51205.8555 - mae: 51205.8555 - val_loss: 50689.4141 - val_mae: 50689.4141
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50634.3242 - mae: 50634.3242 - val_loss: 50464.4492 - val_mae: 50464.4492
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50387.0156 - mae: 50387.0156 - val_loss: 50384.1875 - val_mae: 50384.1875
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50263.2266 - mae: 50263.2266 - val_loss: 50341.8594 - val_mae: 50341.8594
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50176.0469 - mae: 50176.0469 - val_loss: 50319.0117 - val_mae: 50319.0117
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50116.7031 - mae: 50116.7031 - val_loss: 50299.4688 - val_mae: 50299.4688
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50071.2109 - mae: 50071.2109 - val_loss: 50280.8203 - val_mae: 50280.8203
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50033.2383 - mae: 50033.2383 - val_loss: 50271.7383 - val_mae: 50271.7383
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49998.3633 - mae: 49998.3633 - val_loss: 50253.8516 - val_mae: 50253.8516
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49967.7422 - mae: 49967.7422 - val_loss: 50236.4961 - val_mae: 50236.4961
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49940.9570 - mae: 49940.9570 - val_loss: 50230.6133 - val_mae: 50230.6133
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49913.8047 - mae: 49913.8047 - val_loss: 50225.6836 - val_mae: 50225.6836
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49888.9414 - mae: 49888.9414 - val_loss: 50216.1680 - val_mae: 50216.1680
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49867.9727 - mae: 49867.9727 - val_loss: 50212.1133 - val_mae: 50212.1133
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49848.0469 - mae: 49848.0469 - val_loss: 50204.9141 - val_mae: 50204.9141
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49827.6172 - mae: 49827.6172 - val_loss: 50202.6797 - val_mae: 50202.6797
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49812.4883 - mae: 49812.4883 - val_loss: 50192.2812 - val_mae: 50192.2812
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49792.8438 - mae: 49792.8438 - val_loss: 50187.9961 - val_mae: 50187.9961
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49773.7656 - mae: 49773.7656 - val_loss: 50182.9102 - val_mae: 50182.9102
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49761.1562 - mae: 49761.1562 - val_loss: 50179.6836 - val_mae: 50179.6836
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49744.0195 - mae: 49744.0195 - val_loss: 50173.8359 - val_mae: 50173.8359
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49731.7461 - mae: 49731.7461 - val_loss: 50172.6602 - val_mae: 50172.6602
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49713.9414 - mae: 49713.9414 - val_loss: 50172.5117 - val_mae: 50172.5117
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49704.6055 - mae: 49704.6055 - val_loss: 50174.9609 - val_mae: 50174.9609
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49687.3047 - mae: 49687.3047 - val_loss: 50174.0000 - val_mae: 50174.0000
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49677.2070 - mae: 49677.2070 - val_loss: 50177.8008 - val_mae: 50177.8008
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49663.9297 - mae: 49663.9297 - val_loss: 50168.2578 - val_mae: 50168.2578
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49652.0234 - mae: 49652.0234 - val_loss: 50174.4414 - val_mae: 50174.4414
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49645.3008 - mae: 49645.3008 - val_loss: 50167.8906 - val_mae: 50167.8906
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49634.1914 - mae: 49634.1914 - val_loss: 50154.7734 - val_mae: 50154.7734
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49625.0625 - mae: 49625.0625 - val_loss: 50153.9258 - val_mae: 50153.9258
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49617.2969 - mae: 49617.2969 - val_loss: 50167.5195 - val_mae: 50167.5195
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49610.3750 - mae: 49610.3750 - val_loss: 50166.0234 - val_mae: 50166.0234
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49598.8984 - mae: 49598.8984 - val_loss: 50156.3281 - val_mae: 50156.3281
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49590.3047 - mae: 49590.3047 - val_loss: 50157.4531 - val_mae: 50157.4531
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49589.7305 - mae: 49589.7305 - val_loss: 50150.0898 - val_mae: 50150.0898
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49579.0312 - mae: 49579.0312 - val_loss: 50164.5859 - val_mae: 50164.5859
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49571.2891 - mae: 49571.2891 - val_loss: 50169.5703 - val_mae: 50169.5703
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49562.9453 - mae: 49562.9453 - val_loss: 50156.7461 - val_mae: 50156.7461
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49556.8867 - mae: 49556.8867 - val_loss: 50156.2617 - val_mae: 50156.2617
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49549.1133 - mae: 49549.1133 - val_loss: 50163.4258 - val_mae: 50163.4258
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49545.9844 - mae: 49545.9844 - val_loss: 50159.1445 - val_mae: 50159.1445
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49542.0703 - mae: 49542.0703 - val_loss: 50163.9336 - val_mae: 50163.9336
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49534.2070 - mae: 49534.2070 - val_loss: 50165.1484 - val_mae: 50165.1484
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49527.5469 - mae: 49527.5469 - val_loss: 50175.6953 - val_mae: 50175.6953
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49519.0898 - mae: 49519.0898 - val_loss: 50184.8594 - val_mae: 50184.8594

In [22]:
%load_ext tensorboard

In [25]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 6572), started 0:01:09 ago. (Use '!kill 6572' to kill it.)

In [26]:
test_loss,test_mae = model.evaluate(x_test,y_test)
print(test_mae)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50150.0898 - mae: 50150.0898
50150.08984375

In [27]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.